"""remove unique constraint from crawlrule site

Revision ID: 1a33e1ebe0e5
Revises: 4b2dd12f6ba7
Create Date: 2025-12-04 23:57:13.764505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a33e1ebe0e5'
down_revision = '4b2dd12f6ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crawl_rule', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_crawl_rule_site'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crawl_rule', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_crawl_rule_site'), ['site'])

    # ### end Alembic commands ###
