"""add CrawlRule model

Revision ID: 391e3daf52bf
Revises: acd0bc82fcce
Create Date: 2025-12-04 20:32:29.683456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391e3daf52bf'
down_revision = 'acd0bc82fcce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=256), nullable=False),
    sa.Column('title_xpath', sa.String(length=512), nullable=True),
    sa.Column('content_xpath', sa.Text(), nullable=True),
    sa.Column('headers_json', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site')
    )
    with op.batch_alter_table('collection_detail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_detail_item_id'))

    with op.batch_alter_table('collection_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_item_created_at'))
        batch_op.drop_index(batch_op.f('ix_collection_item_keyword'))
        batch_op.drop_index(batch_op.f('ix_collection_item_source'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_item_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_item_keyword'), ['keyword'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_item_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('collection_detail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_detail_item_id'), ['item_id'], unique=False)

    op.drop_table('crawl_rule')
    # ### end Alembic commands ###
