"""add name to crawlrule

Revision ID: 4b2dd12f6ba7
Revises: ec254f0b3798
Create Date: 2025-12-04 23:41:16.357449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b2dd12f6ba7'
down_revision = 'ec254f0b3798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    with op.batch_alter_table('crawl_rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crawl_rule', schema=None) as batch_op:
        batch_op.drop_column('name')

    op.create_table('article',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=512), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('html', sa.TEXT(), nullable=True),
    sa.Column('url', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('source', sa.VARCHAR(length=256), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###
