"""add crawl rules model

Revision ID: 526983a09a63
Revises: 7873fd709c10
Create Date: 2025-12-04 21:10:55.531882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526983a09a63'
down_revision = '7873fd709c10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=128), nullable=False),
    sa.Column('site_domain', sa.String(length=256), nullable=False),
    sa.Column('title_xpath', sa.String(length=512), nullable=True),
    sa.Column('content_xpath', sa.String(length=1024), nullable=True),
    sa.Column('request_headers', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_domain')
    )
    op.drop_table('collection_rule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_rule',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('site_name', sa.VARCHAR(length=256), nullable=False),
    sa.Column('title_xpath', sa.TEXT(), nullable=True),
    sa.Column('content_xpath', sa.TEXT(), nullable=True),
    sa.Column('request_headers', sa.TEXT(), nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_name')
    )
    op.drop_table('crawl_rule')
    # ### end Alembic commands ###
