"""add AIEngine model

Revision ID: 6b3f0c294e0e
Revises: 1a33e1ebe0e5
Create Date: 2025-12-05 00:41:33.796958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b3f0c294e0e'
down_revision = '1a33e1ebe0e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_engine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('api_url', sa.String(length=512), nullable=False),
    sa.Column('api_key', sa.String(length=512), nullable=True),
    sa.Column('model_name', sa.String(length=256), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_engine')
    # ### end Alembic commands ###
