"""add collection rules model

Revision ID: 7873fd709c10
Revises: 391e3daf52bf
Create Date: 2025-12-04 20:51:35.773380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7873fd709c10'
down_revision = '391e3daf52bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=256), nullable=False),
    sa.Column('title_xpath', sa.Text(), nullable=True),
    sa.Column('content_xpath', sa.Text(), nullable=True),
    sa.Column('request_headers', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_name')
    )
    op.drop_table('crawl_rule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_rule',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('site', sa.VARCHAR(length=256), nullable=False),
    sa.Column('title_xpath', sa.VARCHAR(length=512), nullable=True),
    sa.Column('content_xpath', sa.TEXT(), nullable=True),
    sa.Column('headers_json', sa.TEXT(), nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site')
    )
    op.drop_table('collection_rule')
    # ### end Alembic commands ###
