"""add final_url to detail

Revision ID: 851d77f3b8f7
Revises: 79ab5bbfcf25
Create Date: 2025-12-04 17:24:24.674037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '851d77f3b8f7'
down_revision = '79ab5bbfcf25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_url', sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_detail', schema=None) as batch_op:
        batch_op.drop_column('final_url')

    # ### end Alembic commands ###
