"""extend crawler fields: key/class/base/headers/params

Revision ID: a82054e6845b
Revises: 09b3ea50fc2f
Create Date: 2025-12-05 10:33:48.792283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a82054e6845b'
down_revision = '09b3ea50fc2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crawler', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('class_path', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('base_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('headers_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('params_json', sa.Text(), nullable=True))
        batch_op.create_unique_constraint('uq_crawler_key', ['key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crawler', schema=None) as batch_op:
        batch_op.drop_constraint('uq_crawler_key', type_='unique')
        batch_op.drop_column('params_json')
        batch_op.drop_column('headers_json')
        batch_op.drop_column('base_url')
        batch_op.drop_column('class_path')
        batch_op.drop_column('key')

    # ### end Alembic commands ###
