"""add indexes for product level

Revision ID: acd0bc82fcce
Revises: 851d77f3b8f7
Create Date: 2025-12-04 19:51:39.407843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acd0bc82fcce'
down_revision = '851d77f3b8f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_detail', schema=None) as batch_op:
        batch_op.create_index('ix_collection_detail_item_id', ['item_id'], unique=False)

    with op.batch_alter_table('collection_item', schema=None) as batch_op:
        batch_op.create_index('ix_collection_item_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_collection_item_keyword', ['keyword'], unique=False)
        batch_op.create_index('ix_collection_item_source', ['source'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_item', schema=None) as batch_op:
        batch_op.drop_index('ix_collection_item_source')
        batch_op.drop_index('ix_collection_item_keyword')
        batch_op.drop_index('ix_collection_item_created_at')

    with op.batch_alter_table('collection_detail', schema=None) as batch_op:
        batch_op.drop_index('ix_collection_detail_item_id')

    # ### end Alembic commands ###
