"""add crawler.dynamic_keys column

Revision ID: c8d47e3f37ec
Revises: a82054e6845b
Create Date: 2025-12-05 13:03:43.573956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d47e3f37ec'
down_revision = 'a82054e6845b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crawler', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dynamic_keys', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crawler', schema=None) as batch_op:
        batch_op.drop_column('dynamic_keys')

    # ### end Alembic commands ###
